### ISSUE TITLE
[OFT-02M] Significant Centralization of Supply

### ISSUE THREAD

**Issue by 0xfornax** [Gravita-Protocol/layer-zero#12]
## OFT-02M: Significant Centralization of Supply

| Type | Severity | Location |
| ---- | -------- | -------- |
| [Centralization Concern](/appendix/finding-types#centralization-concern) | <img class="o-severity o-unknown" src="https://omniscia.io/report-assets/unknown.png" /> | [OFTV2.sol:L94-L98](https://github.com/Gravita-Protocol/layer-zero/blob/1564b4d1a2578dd615ec14058a034a3550f91106/contracts/token/oft/v2/OFTV2.sol#L94-L98) |

### Description:

All `OFTV2` deployments across chains are susceptible to a high centralization risk as the `owner` of the contract is capable of arbitrarily assigning contracts with mint and burn rights.

### Example:

```solidity
   function setAddresses(address _borrowerOperationsAddress, address _stabilityPoolAddress, address _vesselManagerAddress) public onlyOwner {
       borrowerOperationsAddress = _borrowerOperationsAddress;
       stabilityPoolAddress = _stabilityPoolAddress;
       vesselManagerAddress = _vesselManagerAddress;
   }

   function setWhitelist(address _address, bool _isWhitelisted) external onlyOwner {
	whitelistedContracts[_address] = _isWhitelisted;

	emit WhitelistChanged(_address, _isWhitelisted);
}
```

### Recommendation:

We advise the ownership system to be revised and a decentralized approach to be utilized, such as a DAO implementation over a singleton address.

**Comment by spider-g** [comment]
Acknowledged. The long-term plan is to achieve full decentralization of the protocol through the implementation of a DAO and the launch of a governance token. Meanwhile, a multisig will be responsible for controlling parameters, allowing for efficient responses to platform changes and risk mitigation.
